### ISSUE TITLE
Items dropped due to death can only be picked up by the original owner

### ISSUE THREAD

**Issue by Dli42** [Vendivar/IslandTrollTribes2#153] opened 2016-05-16 22:57 UTC

**Comment by MNoya** [comment] 2016-05-17 04:33
You mean they can't be picked up at all (any error message?), or that they have ownership problems?

**Comment by Vendivar** [comment] 2016-05-17 04:34
No messages at all.

**Comment by MNoya** [comment] 2016-05-17 13:35
I can't reproduce this in tools. I just did `-createhero huskar enemy` followed by `-givebots item_axe_steel` and after killing it, the item is properly pickable. I think it might be a problem with the order filter, will have to run a multiplayer test to be sure

**Comment by MNoya** [comment] 2016-05-23 02:59
So apparently this is fixed, the only problem remaining with death drops is the gravestone will most of the time block the item hitboxes. I am not sure how to fix this, maybe we need a function to space-out the drops forming a grid so they don't block each other and put the gravestone on the middle.

**Comment by Vendivar** [comment] 2016-05-23 03:05
Can we make a hollowed out circle pattern with the launch loot on death?

**Comment by MNoya** [comment] 2016-05-23 03:14
Yep super doable and should look quite good visuall, will take care of that!

**Comment by MNoya** [comment] 2016-05-23 16:23
![img](http://puu.sh/p2nfP/811672fe86.jpg)

**Comment by MNoya** [comment] 2016-05-23 16:25
![img](http://puu.sh/p2nfP/811672fe86.jpg)

**Comment by Dli42** [comment] 2016-05-23 16:40
What a lovely offering. It looks really nice.

**Comment by Vendivar** [comment] 2016-05-23 16:56
Beautiful

**Comment by MNoya** [comment] 2016-05-23 17:06
I have already pushed it but github seems to be having issues, this should be closed when its actually committed.

**Closed** 2016-05-23 17:08 UTC
Labels: bug, mechanics
